name: FOSSA CLI Analysis + Test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # test
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}

    strategy:
      fail-fast: false
      matrix:
        directory: [ 'test-0', 'test-1', 'test-3', 'test-4', 'test-5'  ]

    steps:
      - uses: actions/checkout@v3
  
#       - name: Running FOSSA CLI
#         run: |
#           curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
#           fossa --version
          
#           if ! fossa analyze ${{ matrix.directory }}; then
#               echo "FOSSA analysis not successful"
#               exit 1
#           fi
      - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        id: fossa-analyze
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

#       - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
#         id: fossa-test
#         with:
#           api-key: ${{secrets.FOSSA_API_KEY}}
#           run-tests: true

      - name: Running FOSSA CLI test with json output
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa --version
          fossa test --json | jq '.issues[] | select(.type == "vulnerability" and .status == "new" and .depth < 3)'
